### ISSUE TITLE
hmmlearn for HMM

### ISSUE THREAD

**Issue by suwangcompling** [hmmlearn/hmmlearn#134]
Hi Sergei,

Thanks for the great work with the HMM library.
I am a linguistics student. I'm trying to use hmmlearn to create a POS tagger, and I have a corpus which is a list of word-tag pairs. I built a tag-tag transition probability matrix and a tag-word emission probability matrix, but am having difficulty figuring out the correct syntax to train an hmm model. Could you give me a simple example for the task?

Thanks!
Jacob

**Comment by superbobry** [comment]
Hi Jacob,

`hmmlearn` currently only targets unsupervised learning scenario. In the context of POS tagging that would be to infer the tags automatically given only a list of words. Since you're after supervised learning, I suggest to check out [`seqlearn`](https://github.com/larsmans/seqlearn), which implements supervised learning of [HMMs](http://larsmans.github.io/seqlearn/reference.html#seqlearn.hmm.MultinomialHMM).

**Comment by aikramer2** [comment]
I would also consider conditional random fields for this task. They're quite flexible to arbitrary sequence structures, and are easier to train.

**Comment by suwangcompling** [comment]
Thanks superbobry, aikramer.
I have a CRF and a RNN-based classifier. Since both are discriminative, I'm thinking exploring the idea of Generative Adversarial Model, and use an HMM as a start-off generative classifier.
