### ISSUE TITLE
Can I perform online learning by consecutive executions of `fit()`?

### ISSUE THREAD

**Issue by aghasemi** [hmmlearn/hmmlearn#195]
Hi,
Suppose more sequences of observations arrive over time. How can I update/improve model parameters by online training over only the newly-arrived observations? Is it possible or the only way is to redo the whole training with all sequences?

**Comment by pakelley** [comment]
I'm not an expert on the details, but I think what you're looking for is the 'init_params' argument. More info here: https://hmmlearn.readthedocs.io/en/latest/api.html?highlight=verbose#gaussianhmm

**Comment by pakelley** [comment]
I'm not an expert on the details, but I think what you're looking for is the 'init_params' argument. More info here: https://hmmlearn.readthedocs.io/en/latest/api.html?highlight=verbose#gmmhmm

It defaults to the string 'stmcw', where the letters refer to
s: startprob
t: transmat
c: covars
w: mixing weights(if you're using GMMHMM, otherwise ignore this value)
(e: emmissionprob for MultinomialHMM)

Taking out a letter takes out the initialization of that variable though. Hope it helps!
