### ISSUE TITLE
hmmlearn used unseen data when predicting?

### ISSUE THREAD

**Issue by nerdylinius** [hmmlearn/hmmlearn#196]
I found a strange problem when using  a pre-trained GaussianHMM model to predict new data sequentially. Firstly, a state sequence (s1, s2, s3) is predicted as (l1, l1, l1), however a new sequence (s1, s2, s3, s4) is predicted as (l1, l1, l2, l2). So I am confused why should s3's state have changed? It violated the rule of Viterbi.

**Comment by superbobry** [comment]
The Viterbi invariant that V[t, i] contains the optimal state sequence for observations 1 to t-th ending in state i. To get the optimal path for T observations you

* compute V[t, i] for all t and i;
* take the argmax for t = T (last observation)
* and backtrack from there to obtain the path. 

Note that the resulting path is not necessarily a subpath of the optimal path for T + 1 observations, because to compute V[T + 1, i] you would use the whole row V[T, i] and not just the argmax(V[T, i]).

Hope this helps.
