### ISSUE TITLE
Determining the right number of states for a multinomial HMM

### ISSUE THREAD

**Issue by Nedervino** [hmmlearn/hmmlearn#208]
I want to predict the likelihood of a new sequence given a fitted model. The dataset contains sequences of 41 different observations (It's a dataset of user clickstream path sequences, with 41 options to click). How should I determine the number of states for my HMM? I have already fitted the model using an arbitrarily chosen number of states, but have no clue what the number should be or how I can optimize this using hmmlearn

**Comment by Zhijing1128** [comment]
I think you can try more and find the one with the max likelihood, which means it fits the best.

**Comment by superbobry** [comment]
As far as I know there is no good recipe for choosing the number of states, unless you have some expectations about the True Number from the domain knowledge. 

Using likelihood wouldn't work because a model with more states always (over)fits the data better. You could look into asymptotic criteria ([AIC](https://en.wikipedia.org/wiki/Akaike_information_criterion)/[BIC](https://en.wikipedia.org/wiki/Bayesian_information_criterion)), but if the dataset is big enough, the effect of the penalty they impose would be negligible.
