### ISSUE TITLE
Deploy Continuous and Multinomial features at the same time?

### ISSUE THREAD

**Issue by airpingu** [hmmlearn/hmmlearn#21]
Currently we can have GaussianHMM and MultinomialHMM models to use. However it seems to me that the observed features have to be a single type under one model. That is, either Continuous or Multinomial. No hybrid.

Hope to see we can deploy Continuous and Multinomial features in a mixture way. This is very useful because the feature types can be various and we need different ways to model them.

**Comment by superbobry** [comment]
I'm not sure I've correctly understood your solution. You want to split the multinomial feature into N separate 0/1 features and model them with a Gaussian? This might work, because in the limit everything tends to look like a Gaussian, but I'm not completely sure. 

So if it works badly, you might want to try an HMM which uses Gaussians for **some** of the features and Multinomials for the remaining features. This should be possible because the HMM allows doesn't care about the specific distribution of your features (given the state). Start with `BaseHMM` and redefine:

* `_compute_log_likelihood`
* `_generate_sample_from_state`
* `_init` 
* `_accumulate_sufficient_statistics` and
* `_do_mstep`.

This might look like a lot of code, but fear not! In fact you should be able to re-use these methods from `GaussianHMM` and `MultinomialHMM` as long as your class defines the same attributes.

If your features aren't Gaussian or Multinomial you can implement any other exponential-family distribution by redefining the same set of methods.

**Comment by airpingu** [comment]
> I'm not sure I've correctly understood your solution. You want to split the multinomial feature into N separate 0/1 features and model them with a Gaussian? This might work, because in the limit everything tends to look like a Gaussian, but I'm not completely sure.

I apologize for deleting my solution in my previous comment because I don't think I've already completely thought over it. Now that you responded to that I'd like to clarify more.

Yes, you're most right but I think it's supposed to be N*2 Gaussian nodes. For example, supposing we have 3 multinomial states, I would use 6 continuous nodes to model them, which represents ```[state_1_false, state_1 true, state_2_false, state_2 true, state_3_false, state_3 true]```

For example, if the observed state is 2, then the feature vector is [0, 0, 0, 1, 0, 0]. This can ensure the learned mean is exactly either 0 or 1, instead of a continuous value in between.

> So if it works badly, you might want to try an HMM which uses Gaussians for some of the features and Multinomials for the remaining features.

I see. Thank you for the hint.
