### ISSUE TITLE
what's the difference between the hmmlearn and seqlearn ..

### ISSUE THREAD

**Issue by bboalimoe** [hmmlearn/hmmlearn#29]
and the hmmlearn seems to be able to realize the supervised learning

**Comment by superbobry** [comment]
Yes, the API for supervised learning however is not currently implemented.

**Comment by larsmans** [comment]
seqlearn is my attempt to provide sequence classification with a proper API. The API in hmmlearn is too different from the scikit-learn conventions (which is why it was split off in the first place), and not very extendable. seqlearn has a structured perceptron for learning something close to a CRF and I couldn't have implemented that with the hmmlearn API. There's also a pull request with a true CRF implementation, but I don't have time to maintain the package.

(The HMM in seqlearn is really there for completeness. I don't use HMMs, they don't work for me.)

**Comment by bboalimoe** [comment]
@superbobry so.. can i use the fit method in gmmhmm of hmmlearn to construct a prediction model and use the score method to predict the label of the sequence i want to classify? 
thanks a lot~
and  @larsmans maybe i can check the crf pull requests~

**Comment by superbobry** [comment]
@bboalimoe you can do that, yes, but only in unsupervised way.

@larsmans can you please elaborate a bit on the downsides of hmmlearn API compared to sklearn?

**Comment by bboalimoe** [comment]
@superbobry so... it confuses me a little..that what is the difference between the supervised and unsupervised in hmm model prediction..
for my thoughts..  we use the same label sequences to train one set of hmm model parameters. and when we predict the label of one sequence, i put it into different trained models to get the log probability of the sequence in different models. And then i label the sequence with the highest probablities of the trained model~ 
is the above right~ thanks

**Comment by larsmans** [comment]
In hmmlearn, you feed a list of arrays to `fit`: a 3-d structure. That doesn't work with scikit-learn transformers unless you jump through hoops to wrap a 2-d array in this kind of structure. Similarly, `predict` always takes a single sequence rather than a sequence of sequences, making evaluation harder.

In seqlearn, I decided to stick to the 2-d `X` and 1-d `y` convention to denote a set of samples. The only difference with scikit-learn is that the order matters (but transformers will always respect the ordering) and that sequence start/end points are given in an optional extra argument. In theory, a seqlearn classifier can fit right into a `Pipeline`.

**Comment by janitanjaria23** [comment]
I am using the scikit learn HMM module , and getting the "ValueError: Rows of transmat must sum to 1.0" , can someone help me with the same and also tell me what are the changes that need to be made if we want to shift to using hmmlearn in place of scikit learn .

**Comment by superbobry** [comment]
Hello @janitanjaria23. Which version of Python, NumPy, SciPy and `hmmlearn` are you using?
