### ISSUE TITLE
GaussianHMM import error

### ISSUE THREAD

**Issue by elysiumfield** [hmmlearn/hmmlearn#325]
The line

from hmmlearn.hmm import GaussianHMM

is now returning

ImportError: cannot import name 'distribute_covar_matrix_to_match_covariance_type'.

I suspect this is due to update in scikit-learn (0.20.1). Is it possible to fix or round?

**Comment by anntzer** [comment]
This is fixed on hmmlearn 0.2.1.

**Comment by elysiumfield** [comment]
@anntzer I have ver 0.2.1, installed using conda install -c omnia. The line

from sklearn.mixture import distribute_covar_matrix_to_match_covariance_type

is still causing the problem. Also updating scikit-learn to 0.20.2 does not help.

**Comment by anntzer** [comment]
What does `conda list` show as version and as channel for hmmlearn?  I don't see an hmmlearn 0.2.1 at https://anaconda.org/omnia/hmmlearn/files.  (But they have a hmmlearn 0.3.0b which doesn't exist either... I can't do anything if they start inventing their own releases.)

**Comment by elysiumfield** [comment]
@anntzer conda list shows ver 0.3.0b, but hmmlearn.__version__ shows 0.2.1.
Actually my first attempt was to download from
https://www.lfd.uci.edu/~gohlke/pythonlibs/#hmmlearn
and tried both hmmlearn‑0.2.1‑cp36‑cp36m‑win_amd64.whl and hmmlearn‑0.2.1‑cp37‑cp37m‑win_amd64.whl. Both returned the same import error message.

Is there an updated version of hmmlearn, other than the ones I have listed here? I prefer an installation that doesn't require c++ compiler.

**Comment by anntzer** [comment]
Gohlke's hmmlearn 0.2.1 was published on his website on July 20th, 2018, which is before hmmlearn 0.2.1 was actually published (https://pypi.org/project/hmmlearn/#files shows that it was published on October 17th, 2018).  So it cannot be the actual hmmlearn 0.2.1, just like omnia's hmmlearn cannot be hmmlearn 0.3.0b because that version doesn't exist.

Frankly I cannot do anything if people package random stuff (I guess it's just the state of the repository whenever they packaged it) and add a random tag on it.

I don't have the bandwidth to set up building wheels for all three platforms right now.

You may have a better chance contacting omnia or conda-forge and ask them to package the actual hmmlearn 0.2.1.

**Comment by elysiumfield** [comment]
That was indeed very confusing with the various weird versions. Anyway, to get the official release of ver 0.2.1, can you confirm that I can do the following steps:

1, Install Build Tools for Visual Studio 2017
2. pip install -U --user hmmlearn==0.2.1

I think it's better just to install the compiler, rather than waiting for others to package it.

Thanks a lot for your fast replies!

**Comment by cgohlke** [comment]
I updated the wheel to the final 0.2.1 version. The import error is fixed. The previous wheels were built from the git master branch (probably because it worked better than 0.2.0 at that time) and the "weird version" came from the `hmmlearn\__init__,py` file. I must have missed the GitHub notification for the actual release...

**Comment by anntzer** [comment]
Thank you *very* much Christoph for your quick action!
I did forget to push a 0.2.1 tag on the repo itself (I had it locally only and just pushed it when this issue was opened) and didn't realize you were getting the notifications from them; now I'll know.

**Comment by elysiumfield** [comment]
This is great news. Thank you both!
