### ISSUE TITLE
Cannot run GMMHMM with high number of mixtures

### ISSUE THREAD

**Issue by tnnandi** [hmmlearn/hmmlearn#348]
I'm trying to use Gaussian Mixture Model using the following configuration for a time series with 49792 samples:

model = GMMHMM(n_components=40, n_mix = 5, tol = 1e-6, covariance_type = "full", n_iter=100, verbose=True)

I get the following error: ValueError: n_samples=3 should be >= n_clusters=5

I cannot comprehend why n_samples = 3 because of which the error is being thrown (It seems during the initial random clustering, the number of samples in some clusters become very less). Is there any way to get around this problem?

Also, can someone please let me know what does the columns 2 and 3 in the output (the first being the iteration number ) in verbose mode represent?

**Comment by hazrmard** [comment]
> Also, can someone please let me know what does the columns 2 and 3 in the output (the first being the iteration number ) in verbose mode represent?

From the documentation of [`ConvergenceMonitor`](https://hmmlearn.readthedocs.io/en/latest/api.html#hmmlearn-base):

> The output consists of three columns: iteration number, log probability of the data at the current iteration and convergence rate. At the first iteration convergence rate is unknown and is thus denoted by NaN.

Also note, from the documentation on log-probabilities:

> If the values are not strictly increasing, the model did not converge.

The convergence rate is just the change in log-probability between iterations.

**Comment by Naowak** [comment]
Hello, 

I got that error too, and it takes me a few hours to finally find what was going wrong.
In the first steps of the algorithm, it will try to split all values from your data into "n_components" clusters, so that each components could have a range of value that suits to him. (This is necessary if you want your component to learn GMM). It will use K-means to do that task.

But, if the number of components that you ask doesn't suit to the problem, some cluster will end up with very few values. If this happend, one way to avoid it is to reduce or increase the "n_components" so that it suits better to the problem.
To find the right number of components, you can visualise your data.

I hope that could help.

**Comment by FirstHandScientist** [comment]
Hi, 
It seems GMMHMM is not fully implemented. The _accumulate_sufficient_statistics does not accumulate multiple sequence data, but just one sequence. ( There is also a todo there)
I observe log likelihood value drop when running data contains multiple sequence.

**Comment by anntzer** [comment]
Given the comment above, I will assume that #417 fixed the problem. If not, please provide a reproducible example.
