### ISSUE TITLE
AttributeError: 'GaussianHMM' object has no attribute 'n_features' for spherical covariance type

### ISSUE THREAD

**Issue by andrzejchomiczewski** [hmmlearn/hmmlearn#385]
While trying to get covars from model defined as follows:
```python
HMM2 = hmm.GaussianHMM(n_components=2, covariance_type="spherical")
HMM2.startprob_ = np.array([0.6, 0.4])
HMM2.transmat_ = np.array([[0.4, 0.6],
                           [0.9, 0.1]])
HMM2.means_ = np.array([[3.0],[5.0]])
HMM2.covars_ = np.array([[[[4.0]]], [[[3.0]]]])
```
The following error occurs:
AttributeError: 'GaussianHMM' object has no attribute 'n_features'

After calling command: 
```python
HMM2.covars_ 
```
or calling
```python
HMM2.sample(100)
```
yields following error:
ValueError: cov must be 2 dimensional and square

In that particular case covariance can't be 2 dimensional and square, as it is explicitly defined as a single value.

Which is strongly counter-intuitive, as this type of HMM has 1 feature. Any help with solving that issue would be appreciated.

**Comment by anntzer** [comment]
Please provide a *complete* reproducing example, per https://github.com/hmmlearn/hmmlearn/blob/master/.github/ISSUE_TEMPLATE.md#i-am-reporting-a-bug.

**Comment by andrzejchomiczewski** [comment]
@anntzer Here you go, sorry for misconduct.

**Comment by anntzer** [comment]
thanks.

**Comment by DKaravolos** [comment]
I encountered this AttributeError as well with covariance_type = "full".  But not in the same situation. For me setting the HMM2.covars_ worked fine, but getting it later gave me an error. 


The problem here is that it seems that model.covars_ gives direct access to an internal variable, but it is actually accessed via a get/set function (which is disguised by @property).

The getter requires a HMM2.n_features to determine the shape of the covariance matrix. However, this attribute is not made until the model has seen the data (I think it is made in _check_and_set_gaussian_n_features). That sort of makes sense if you want to automatically derive it from the data, as there is no good default value (though it would be good if all variables exist when the object is initialized).  
You run into the problem when you want to use the model without training it on data (e.g., if the means and covariances are restored from a previous session). 

Perhaps an optional parameter in the constructor would be a solution if users want to use the model without training?
A current workaround for users would be to set the HMM2.n_features manually before setting the HMM2.covars_ (since the n_features attribute is created, this also resolved the getter-problem for me).

I hope this helps.

**Comment by jaryP** [comment]
Hello there,

I encountered the same bug when sampling from a trained GaussianHMM with spherical covariance. 
Since the property covars_ has shape (n_components, 1, n_feature, n_features), I have fixed the problem by changing the following line in the sample() function, from

> X.append(self._generate_sample_from_state(currstate, random_state=random_state))

which tries to use the covariance as a (1, n_feature, n_features) matrix, to

>  X.append(np.random.multivariate_normal(model.means_[currstate], model.covars_[currstate][0])).

basically, the only difference is model.covars_[currstate][0] instead of model.covars_[currstate]
