### ISSUE TITLE
_do_mstep in class GMMHMM

### ISSUE THREAD

**Issue by y-ito-1985** [hmmlearn/hmmlearn#503]
## I have a question

I have a question about optimization of parameter "weight_".
I have checked the results of the operation in following settings.

gmmhmm = GMMHMM(n_components=2, n_iter=100, covariance_type="full")
gmmhmm.fit(seq) # seq: 1-dimensional sequence
print(gmmhmm.weights_)
-- out --
[[1.]
 [1.]]

As a result, parameter "weight_" is an unstandardized value.
I thought I could get two numbers that sum up to 1.
Is this behavior as intended?

If possible, could you also provide a direct reference to the _do_mstep implementation?

**Comment by blckmaxima** [comment]
Hello!  Since you did not specify `n_mix` in the constructor, you are creating a GMMHMM with `1` mixture for each component.  The `weights_` parameter has size `(n_components, n_mix)`, so this is all correct.  Try experimenting with a different value for `n_mix`, and you will see the `weights_` parameter change.
